name: IndrocraftPlugin
version: 1.0
main: indrocraft.indrocraftplugin.Main
api-version: 1.17

commands:
  dev:
    usage: /<command>
    description: for developer testing
    aliases: [int, float, double, string]
  warn:
    usage: /<command>
    description: used by admins to ban users slowly increases the time they are banned for
  home:
    usage: /<command>
    description: lets players save locations then teleport to them
    aliases: [h, sethome, delhome, homelist]
  inspector:
    usage: /<command>
    description: switches player into inspector mode for checking for hackers
    aliases: [i]
  warp:
    usage: /<command>
    description: sends players to a predetermined location
    aliases: [setwarp, delwarp, togglewarp]
  ranks:
    usage: /<command>
    description: handles admin rank commands
    aliases: [r, rank]

permissions:
  inspector:
    description: switches player into inspector mode for checking for hackers
    default: op