name: IndrocraftPlugin
version: 1.0
main: indrocraft.indrocraftplugin.Main
api-version: 1.17

commands:
  dev:
    usage: /<command>
    description: for developer testing
    aliases: [int, float, double, string]
  setRank:
    usage: /<command>
    description: chenges the players name in the game and tablist
    aliases: [namecolour]
  warn:
    usage: /<command>
    description: used by admins to ban users slowly increases the time they are banned for
  home:
    usage: /<command>
    description: lets players save locations then teleport to them
    aliases: [h, sethome, delhome, homelist]