name: IndroMain
version: ${project.version}
main: io.github.indroDevTeam.indroMain.IndroMain
api-version: 1.19
author: skyQuiz

commands:
  home:
    description: Teleports a player to their home
    usage: "Command: /<command> <home_name>"
    aliases:
      - h
  sethome:
    description: Sets a player's home at their current location,
    usage: "Command: /<command> <home_name>"
  delhome:
    description: Deletes a player's home from the list of homes
    usage: "Command: /<command> <home_name>"
  homes:
    description: Lists all of the player's homes
    usage: "Command: /<command>"
  profile:
    description: Displays the player's profile
    usage: "Command: /<command>"

  #Admin commands here