name: IndroMain
version: ${project.version}
main: io.github.indroDevTeam.indroMain.IndroMain
api-version: 1.17

commands:
  sethome:
    usage: /<command>
    description: for developer testing
  home:
    usage: /<command>
    description: lets players save locations then teleport to them
  setwarp:
    usage: /<command>
    description: lets players save locations then teleport to them
  homelist:
    usage: /<command>
    description: lets players save locations then teleport to them
  delhome:
    usage: /<command>
    description: lets players save locations then teleport to them
  delwarp:
    usage: /<command>
    description: lets players save locations then teleport to them
  warp:
    usage: /<command>
    description: sends players to a predetermined location
  info:
    usage: /<command>
    description: gets your own data
  time:
    usage: /<command>
    description: gets the time (why not)

permissions:
  inspector:
    description: switches player into inspector mode for checking for hackers
    default: op