name: IndroMain
version: ${project.version}
main: io.github.indrodevteam.indroMain.IndroMain
api-version: 1.17
author: skyQuiz

commands:
  home:
    description: lets players save locations then teleport to them
    aliases: ["sethome", "delhome", "listhomes", "profile"]
    usage: "Usage: /<command> [args]"

permissions:
  inspector:
    description: switches player into inspector mode for checking for hackers
    default: op