name: IndroMain
version: ${project.version}
main: io.github.indroDevTeam.indroMain.IndroMain
api-version: 1.17
author: skyQuiz

commands:
  home:
    description: Teleports a player to their home
    usage: /<command> <home_name>
    aliases:
      - h
  sethome:
    description: Sets a player's home at their current location,
    usage: /<command> <home_name> [desc]
  delhome:
    description: Deletes a player's home from the list of homes
    usage: /<command> <home_name>
  homes:
    description: Lists all of the player's homes
    usage: /<command>
  profile:
    description: Displays the player's profile
    usage: /<command>

  #Admin commands here