name: IndroMain
version: ${project.version}
main: io.github.indroDevTeam.indroMain.IndroMain
api-version: 1.17
author: skyQuiz

commands:
  home:
    description: lets players save locations then teleport to them
    aliases: ["sethome", "delhome", "listhomes"]
  warp:
    description: sends players to a predetermined location
    aliases: ["setwarp", "delwarp", "listwarps"]
  info:
    usage: /<command>
    description: gets your own data

permissions:
  inspector:
    description: switches player into inspector mode for checking for hackers
    default: op